# Generated by Django 4.0.6 on 2022-09-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='side_image1',
            new_name='side_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='side_image2',
        ),
    ]
